### ISSUE TITLE
Bismillah not found!

### ISSUE THREAD

**Issue by xGabbro** [xGabbro/OrariBem#1]
I can't reach the site, it shows an error: "Bismillah not found!"

**Comment by alex3025** [comment]
God Dog

**Comment by xGabbro** [comment]
Sorry, you have clear the bismillah cache?

**Comment by TheSerialKInder** [comment]
Have you tried to ask Claudio?

**Comment by xGabbro** [comment]
> 
> 
> Sorry, you have clear the bismillah cache?

no...Not it work so much

**Comment by alex3025** [comment]
Ok GUGOL
